#pragma once
#include "sdkconfig.h"
#include "esp_err.h"
#include "output.h"

#ifdef CONFIG_SENSOR_BLE_MEASUREMENT_CACHE_SIZE
#if CONFIG_SENSOR_BLE_MEASUREMENT_CACHE_SIZE < 30
#error "CONFIG_SENSOR_BLE_MEASUREMENT_CACHE_SIZE must be at least 30"
#else
#define SENSOR_BLE_MEASUREMENT_CACHE_SIZE CONFIG_SENSOR_BLE_MEASUREMENT_CACHE_SIZE
#endif
#else
#define SENSOR_BLE_MEASUREMENT_CACHE_SIZE 100
#endif

#ifdef CONFIG_SENSOR_BLE_MEASUREMENT_CACHE_EXPIRY_SECONDS
#if CONFIG_SENSOR_BLE_MEASUREMENT_CACHE_EXPIRY_SECONDS < 60
#error "CONFIG_SENSOR_BLE_MEASUREMENT_CACHE_EXPIRY_SECONDS must be at least 60"
#else
#define SENSOR_BLE_MEASUREMENT_CACHE_EXPIRY_SECONDS CONFIG_SENSOR_BLE_MEASUREMENT_CACHE_EXPIRY_SECONDS
#endif
#else
#define SENSOR_BLE_MEASUREMENT_CACHE_EXPIRY_SECONDS 300 // 5 minutes
#endif

#define SENSOR_BLE_MEASUREMENT_CACHE_EXPIRY_MICROS (SENSOR_BLE_MEASUREMENT_CACHE_EXPIRY_SECONDS * 1000000)

esp_err_t sensor_ble_start(output_enqueue_measurement_fn_t fn);